/**
 * Subject Enumeration
 */
enum Subject {
	"3DT" = "3D Technologie",
	ABP = "ABP",
	ANJ = "Anglický jazyk",
	APE = "APE",
	ASW = "ASW",
	ATM = "ATM",
	AUT = "Automatizace",
	BIO = "Biologie",
	CAD = "CAD",
	CAM = "CAM",
	CIT = "CIT",
	CJL = "Český jazyk",
	EEZ = "EEZ",
	EKO = "Ekonomika",
	ELE = "Elektrotechnika",
	ELM = "ELM",
	ELT = "ELT",
	ELZ = "ELZ",
	ESP = "ESP",
	FYZ = "Fyzika",
	CHE = "Chemie",
	IKT = "Informačně komunikační technologie",
	ITE = "ITE",
	KOC = "KOC",
	KOM = "KOM",
	MAT = "Matematika",
	MET = "MET",
	MIK = "MIK",
	MIT = "MIT",
	MME = "Multimédia",
	MPV = "Multimediální a projektová výchova",
	NEJ = "Německá jazy",
	OPS = "OPS",
	PCS = "PCS",
	PRA = "PRA",
	PRG = "PRG",
	PVP = "PVP",
	PVY = "Průmyslové výtvarnictví",
	RAZ = "RAZ",
	SPS = "SPS",
	STR = "Strojírenství",
	STT = "STT",
	TEV = "Tělesná výchova",
	VCS = "VCS",
	VPR = "VPR",
	WEB = "Webové aplikace",
	ZSV = "Základy společenských věd",
}

export default Subject;
